### ISSUE TITLE
Font align on scaled displays

### ISSUE THREAD

**Issue by youurayy** [DavidXanatos/TaskExplorer#2]
Hi, first of all, thank you for this effort. It's great to have "TaskInfo" back!

When I run the app on my 3840x2160 display scaled to 150%, the font alignment looks like this (font is clipped at the bottom):

![image](https://user-images.githubusercontent.com/588573/62161254-6700b080-b31e-11e9-9388-8b6836f6f58f.png)

![image](https://user-images.githubusercontent.com/588573/62161371-aaf3b580-b31e-11e9-8654-6bffcc1a7278.png)

P.s.: why QT? If this is only a Windows app, would it make sense to use the native Windows GUI?
Another advantage of that would be getting a nicely anti-aliased fonts.

**Comment by DavidXanatos** [comment]
The issue should be fixed in the 0.6 build.

Why QT?
Because it does not have to be a windows only app.
there is not a single one even half decent task manager for linux, so its time someone makes one.
Having at least a complete UI is a good start point to start implementing a powerfull backend.
