### ISSUE TITLE
[REQUEST] Can we get that icon love from Sandboxie-Plus?

### ISSUE THREAD

**Issue by Valinwolf** [DavidXanatos/TaskExplorer#22]
I would love to see the icons for TE updated too. 😄

**Comment by DavidXanatos** [comment]
Here are the old icons: https://github.com/DavidXanatos/TaskExplorer/tree/master/TaskExplorer/Resources/Actions
find me a new set you like on icons8.com and I'll consider adding them just like it was with SbiePlus.

**Comment by Valinwolf** [comment]
I'll do that tonight! I'm probably going to pick from the same icon set, fluent.

**Comment by DavidXanatos** [comment]
how is teh picking going ;)

**Comment by Valinwolf** [comment]
Sorry mate I got held at work then I took my mom to the hospital Christmas Eve. (She's ok)
I'll get to it as soon as I can.

**Comment by Valinwolf** [comment]
So I found most of the icons, but there were a few that were not available. I have submitted a request to have them created in the Fluent design. I've [gotten started on a list](https://icons8.com/icons/share-collections/PZfDKpi6THmX), but it's obviously missing a few.

Here is the list of icons missing:
- filter2
- find_dll
- find_handle
- find_string
- fw_mon
- reboot2
- reboot3
- run_as
- run_root
- run_ti
- run_user
- shutdown2
- shutdown3

Like I said, I've already submitted a request for them to be added to the Fluent design set. I could combine a couple of the icons together to make those icons if I had access to the SVG formats. The maximum I can get is a 100px square PNG and I don't like working with images that tiny. If you want to get me the SVGs to make the proper icons, here is the list I would need:
- [Bookshelf](https://icons8.com/icon/hOy6rvBnl5Jv/book-shelf)
- [Looking Glass](https://icons8.com/icon/KPmthqkeTgDN/search)
- [Wall](https://icons8.com/icon/UV4sM0mzsq9p/block)
- [Eye](https://icons8.com/icon/CWkCzh9aKpqb/eye)
- [Processor](https://icons8.com/icon/aBK2UoN0jk4I/processor)
- [Link](https://icons8.com/icon/n9d0Hm43JCPK/link)
- [Restart](https://icons8.com/icon/bDkQlpOV2TWB/restart)
- [Lightning](https://icons8.com/icon/GtgqQIYSqT50/lightning-bolt)
- [Cog](https://icons8.com/icon/s5NUIabJrb4C/settings)
- [Run](https://icons8.com/icon/7XI6kQrF2s0K/run-command)
- [User](https://icons8.com/icon/GwYVu5UZRjBe/user-male)
- [Check](https://icons8.com/icon/VFaz7MkjAiu0/checkmark)
- [Exclamation](https://icons8.com/icon/VbHk5FdAyj8k/exclamation-mark)
- [Red X](https://icons8.com/icon/OZuepOQd0omj/delete)
- [Shutdown](https://icons8.com/icon/IwZ4mbmrC5gw/shutdown)
- [Freeze](https://icons8.com/icon/Mvbzy3ZDRcVj/snowflake)

It wouldn't take me long at all to get those icons created since the legwork would already be done. It would really be a matter of just using Adobe Illustrator to arrange them together and export to SVG or PNG or whatever format(s) you wanted.

**Comment by DavidXanatos** [comment]
build 1.4.0 has new icons :D

**Comment by Valinwolf** [comment]
Sweeeeet!! Can't wait to update when I get home tonight!! 😁

You are by far one of my favorite devs bro!
