### ISSUE TITLE
Falied to decrypt xprocesshacker.sys

### ISSUE THREAD

**Issue by krisavi** [DavidXanatos/TaskExplorer#23]
I did upgrade from 1.2.1
Upon starting as admin I get:
"Failed to decrypt xprocesshacker.sys.rc4 ensure app directory is writable."

Which directory is it talking about? The app directory in "C:\Program Files" is writable, so I have even no idea what other directory to check for writability any more.

**Comment by DavidXanatos** [comment]
C:\Program Files\TaskExplorer\x64
and you need to tart it as admin
ensure the xprocesshacker.sys.rc4 is present and if there is a xprocesshacker.sys delete it

**Comment by krisavi** [comment]
Oh yeah, I got that one fixed, renamed the old xprocesshacker.sys to something else. Probably that occurred due to upgrade process.
