### ISSUE TITLE
[Bug] Can't load xprocesshacker.sys

### ISSUE THREAD

**Issue by H4M5TER** [DavidXanatos/TaskExplorer#28]
I can reproduce the problem with or without my antivirus software.
My antivirus software detect services.exe (called by wininit.exe) is trying to modify registry (to add xprocesshacker service) and allowed it.
But it didn't appeared in services or registry.

![H~O`1TPC@L{ `$T60HBN1OI](https://user-images.githubusercontent.com/21092951/130293298-b58b31f3-325f-4560-bc7e-a0262275d15a.png)
![_QT8$Y3}Q8@6R2${F1YJ{V1](https://user-images.githubusercontent.com/21092951/130293321-1d8d934f-2409-4f88-8ffe-c03a3c674b42.png)
![image](https://user-images.githubusercontent.com/21092951/130293364-61170174-a586-491a-b980-26258185a0a3.png)
![JYD)O8H02DI_{}X2QA05FY2](https://user-images.githubusercontent.com/21092951/130293387-61d71279-b2f0-48b4-988f-8439a20cfad4.png)
![NAQI_)3PBD 0N$PVO_2`XE4](https://user-images.githubusercontent.com/21092951/130293394-3d05372a-feb7-4ff2-b180-a731efc3bb15.png)

**Comment by DavidXanatos** [comment]
Well with a recent update MSFT has blacklisted various leaked code signing certificates in the kernel so for the time being the driver cant be loaded, unless you enable test signing mode

**Comment by H4M5TER** [comment]
bump

**Comment by DavidXanatos** [comment]
release 1.4.0 provides a proeprly test signed driver with a random self generated test cert so it should load on new windows with test signing one, please try

**Comment by H4M5TER** [comment]
it worked. thx
