### ISSUE TITLE
Dozens of fail messages pop up when unistalling

### ISSUE THREAD

**Issue by ibin7777** [DavidXanatos/TaskExplorer#42]
![image](https://user-images.githubusercontent.com/64576479/183257552-fe19698e-e3dc-4498-8785-93e4b6256282.png)
There are more than 20 of these popped up when I try to unistall.
But the unistallation seems ok afterwards.

**Comment by ibin7777** [comment]
Btw the Chinese characters in the screenshot says Access denied.

**Comment by DavidXanatos** [comment]
well did you close te before uninstaling?

**Comment by ibin7777** [comment]
> well did you close the before uninstaling?

Nope, I did not, just discovered it's still running in stray...
