### ISSUE TITLE
1.5.1 - Installer issue

### ISSUE THREAD

**Issue by bovirus** [DavidXanatos/TaskExplorer#45]
@DavidXanatos 

Instakller of 1.5.1 don't create teh righht icon to run teh application from program group or from icon ond ektop.

This issues because program rn point to

C:\Program Files\Task Explorer\x86\TaskExplrorer\TaskExplorer.exe

that is miisng instead

C:\Program Files\Task Explorer\x64\TaskExplrorer\TaskExplorer.exe

Note: also portable version has "TaskExplorer.exe" missing in x86 subfolder.

**Comment by DavidXanatos** [comment]
fixed installer reuploaded
