### ISSUE TITLE
Improvement - Multilanguage application GUI

### ISSUE THREAD

**Issue by bovirus** [DavidXanatos/TaskExplorer#46]
@DavidXanatos 

The program is based on QT SDK.

Pelase consider to enable in TaskExplorer source code the use of multilanguage GUI,

With Qt is quite easy and you can use external .ts/.qm external language file.

**Comment by DavidXanatos** [comment]
the support is already in you can put your *.qm files in the "/translations/" sub folder in the installation dir and then you can pick them in the settings

**Comment by bovirus** [comment]
@DavidXanatos 

Thanks for the info.

I propose you to add in main page of github repository a section

**Translation**

where you put info about current translation status and how to edit/add new translation.

Question: the .ts contain strings for the installer?
How can help you to make the installer multilanguage?

Thanks.

**Comment by bovirus** [comment]
@DavidXanatos 

I didnt' find any .qm language files in installation directory.

Where are the .qm language files?

Or did you inlude them in exe file?

How can try/check my translation using an external .qm language file?

**Comment by bovirus** [comment]
@DavidXanatos 

I staeted translation of **taskexplorer_it.ts**.
I created the **taskexplorer_it.qm** from **taskexplorer_it.ts**
I created a subfodler **translations** under **x64** folder.
I started **taskexplorer.exe** in **x64** folder but it didn't show strings translated.

**Comment by bovirus** [comment]
@DavidXanatos 

Please check source code.
I cannot continue translation if I cannoit see the result of translation and check the context.

**Comment by bovirus** [comment]
@DavidXanatos

Could you please check source code to enable use of external .ts language files?
I'd like to continue the italian translatiuon but I want toi check it.

**Comment by DavidXanatos** [comment]
you need to compile the files to qm files in order for them to be loaded,
i dont think qt can load a uncompiled ts file
to create a qm file you use the lrelease.exe

cheers
david

**Comment by bovirus** [comment]
@DavidXanatos

I know it very well because is not the first  time that I'm using .ts/.qm files.
Please read some post before.
I compiled .ts as .qm and copy it in translation folder.
But when I run TaskExplrorer window I didn't see the strings that I translated.

**Comment by DavidXanatos** [comment]
ah I see, can you please send me the begone translation ts file so I can test with it

**Comment by bovirus** [comment]
@DavidXanatos 

TS file - https://mega.nz/file/icxk2KSC#fxLEEHxxk0it8cNg_4LMk8rQo8Vt-eA43PRpxcquhpI

QM file - https://mega.nz/file/HAwEzSpC#3zMkW4GOZqdpGALFoiry-z4xfNVCKRtfkqajkYa2lTA

**Comment by DavidXanatos** [comment]
hmm... for me the qm file you provided seams to work just fine:
![grafik](https://user-images.githubusercontent.com/3890945/210265689-192f7817-1466-43f8-a267-59dea1cbe4c0.png)

**Comment by bovirus** [comment]
@DavidXanatos 

Where di you get .qmx file?

**Comment by bovirus** [comment]
@DavidXanatos

Found the issue.

Generally qt program didn't require to chnage the language of the interfacei because qt detect OS language and enable by default (if available) GUI of same language of OS.

In your application it didn't work in this way.
You should change manually the language and restart the application.
Why this behaviour?
I beleiev that tehdefault qt behaviour (detact OS language and use by default is availble same OSlanguage of OS) is better.

Thanks.

**Comment by DavidXanatos** [comment]
> @DavidXanatos
> 
> Where di you get .qmx file?

I just renamed the one I compiled such as not to have two and avoid conflicts
