### ISSUE TITLE
Improvement - Change default installation folder to ProgramData

### ISSUE THREAD

**Issue by bovirus** [DavidXanatos/TaskExplorer#47]
@DavidXanatos 

I propsoe to change the installation folder from

**Progra,m Files**

to

**ProgramData**

less problem about file/folder rights and more logical to have

**ProgramDat\x86**

file/fodlers then

**Program Files\x86** (32bit ptogtram fiels in program Fiels that are for 64bit application).

**Comment by DavidXanatos** [comment]
The thing is we need the 32 bit files even on a 64 bit system to take crash dumps of 32 bit programs and alike
also its good to have all the files close together. hence I'll leave it as is
