### ISSUE TITLE
TaskExplorer crashed on open

### ISSUE THREAD

**Issue by terri007** [DavidXanatos/TaskExplorer#5]
OS: Windows 7 Enterprise SP1 64 bit
Task Explorer 0.9.50 (x64)

I have tried to open the app 4 times. Four times it immediately crashed with a message on the attached screenshot. It has created 4 different crash dumps (also attached).

I liked the interface. The info on the processes this app could provide is of interest to me.

Thank you,
[Terri]

I have appended the .dmp with .zip to upload them. Uploading of the .dmp files is not supported.
[TaskExplorer 25.09.2019 23-34-23,949.dmp.zip](https://github.com/DavidXanatos/TaskExplorer/files/3659874/TaskExplorer.25.09.2019.23-34-23.949.dmp.zip)
[TaskExplorer 25.09.2019 23-34-39,719.dmp.zip](https://github.com/DavidXanatos/TaskExplorer/files/3659875/TaskExplorer.25.09.2019.23-34-39.719.dmp.zip)
[TaskExplorer 25.09.2019 23-35-13,261.dmp.zip](https://github.com/DavidXanatos/TaskExplorer/files/3659877/TaskExplorer.25.09.2019.23-35-13.261.dmp.zip)
[TaskExplorer 25.09.2019 23-39-28,037.dmp.zip](https://github.com/DavidXanatos/TaskExplorer/files/3659878/TaskExplorer.25.09.2019.23-39-28.037.dmp.zip)

 
![Crash message](https://user-images.githubusercontent.com/55856900/65724595-c230f400-e07e-11e9-8a55-b66607e12253.png)

**Comment by DavidXanatos** [comment]
hmm.... it crashes while doing reverse dns lookups for the remote host name columns,strangely when  I test it on a Windows 7 sp1 VM the issue does not appear.

Try this build I added an additional check before the place where it crashed may be its that...
[TaskExplorer.zip](https://github.com/DavidXanatos/TaskExplorer/files/3665234/TaskExplorer.zip)

Cheers
David X.

**Comment by terri007** [comment]
This version worked like charm. It is stable now.
With your permission I'd like to play with it to learn its capabilities.
Thank you,Anthony

    On Saturday, September 28, 2019, 4:34:08 AM EDT, DavidXanatos <notifications@github.com> wrote:  
 
 
hmm.... it crashes while doing reverse dns lookups for the remote host name columns,strangely when I test it on a Windows 7 sp1 VM the issue does not appear.

Try this build I added an additional check before the place where it crashed may be its that...
TaskExplorer.zip

Cheers
David X.
