### ISSUE TITLE
Build 1.5.5 doesn't work in Windows 10 22H2

### ISSUE THREAD

**Issue by BlueDrakoPT** [DavidXanatos/TaskExplorer#54]
Doesn't work (with or without driver!) Back to 1.5.3. This new version is a complete disaster!!!!

**Comment by DavidXanatos** [comment]
Please specify what issues do you have?

**Comment by BlueDrakoPT** [comment]
I have no issues! Version 1.5.5 doesn't start at all. (do not run al all) - Starting as Admin, let me see the window to put windows in test mode for driver working - WTF???? test mode???? Please erase this version. 1.5.3 is perfect!!!

**Comment by DavidXanatos** [comment]
have you tried starting it as admin, i.e. use run as admin, I think that might be the issue

**Comment by BlueDrakoPT** [comment]
David Jones reported the same problem here (https://www.patreon.com/posts/task-explorer-v1-103563016)
I'm not alone... :-/

**Comment by BlueDrakoPT** [comment]
My last test is use it as portable (without install). Give you feedback in a few minutes...

**Comment by BlueDrakoPT** [comment]
event log when running app in portable mode with admin privileges:

Faulting application name: TaskExplorer.exe, version: 1.0.0.1, time stamp: 0x663502b1
Faulting module name: ntdll.dll, version: 10.0.19041.4355, time stamp: 0x35a939aa
Exception code: 0xc0000409
Fault offset: 0x00000000000a4ff8
Faulting process id: 0x3238
Faulting application start time: 0x01da9d86665d2965
Faulting application path: C:\TempDir\TaskExplorer\x64\TaskExplorer.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 920e01a7-b634-46bd-b5cd-fe27ad2f910c
Faulting package full name: 
Faulting package-relative application ID:

**Comment by DavidXanatos** [comment]
try this one: https://github.com/DavidXanatos/TaskExplorer/releases/download/v1.5.5/TaskExplorer-1.5.5a.exe

**Comment by BlueDrakoPT** [comment]
This one worked without problems! You're back in track... thanks!

**Comment by BlueDrakoPT** [comment]
test in Windows 11 machine: works well (installed mode or portable mode) . You are forgiven! Hehe.
