### ISSUE TITLE
[Feature Request] Toggle using process binary name only vs process description

### ISSUE THREAD

**Issue by quangkieu** [DavidXanatos/TaskExplorer#9]
Hey DavidXanatos,
I wonder if we could have a checkbox in setting for using process binary name over process description.
Right now on the Process column, we have {{Process Description (Process Binary)}}. I wonder if we could have a switch to change to {{Process Binary (Process Description)}}
As I would like to type out the Process Binary that I am looking for when focus on the Process column.
Right now I have to type out the Process Description like "Windows Powershell" instead of "powershell" to jump to a powershell process.

**Comment by DavidXanatos** [comment]
I will add that to the next build unless I forget it

**Comment by DavidXanatos** [comment]
In the next build there will be a combo box in he settings allowing to choose between:
{{Process Description (Process Binary)}}
{{Process Binary (Process Description)}}
{{Process Binary}}
